import { SeoHead } from '../components/SeoHead';
import { Breadcrumbs } from '../components/Breadcrumbs';
import { LocalRentalDetails } from '../components/LocalRentalDetails';
import { QuoteForm } from '../components/QuoteForm';
import { SITE_IMAGES, getWhatsAppLink } from '../config/siteConfig';

export const SAO_MATEUS_PATH = '/aluguel-de-cacamba/sp/sao-paulo/sao-mateus/';
export function SaoMateusPage() {
  return <div>
    <SeoHead title="Aluguel de Caçamba em São Mateus, São Paulo | Fortera" description="Consulte locação de caçamba de entulho em São Mateus, São Paulo. Tamanhos, aluguel por dias ou meses e troca semanal. Orçamento pelo WhatsApp." path={SAO_MATEUS_PATH} jsonLd={{'@context':'https://schema.org','@type':'Service',name:'Locação de caçamba em São Mateus, São Paulo',serviceType:'Aluguel de caçamba de entulho',areaServed:{'@type':'Place',name:'São Mateus, São Paulo, SP, Brasil'},provider:{'@id':'https://forteracacambas.com/#organization'}}}/>
    <Breadcrumbs items={[{name:'Atendimento',href:'/atendimento/'},{name:'São Paulo — SP',href:'/aluguel-de-cacamba/sp/sao-paulo/'},{name:'São Mateus'}]}/>
    <section className="bg-[#10263D] text-white py-12"><div className="max-w-7xl mx-auto px-6 grid lg:grid-cols-2 gap-8 items-center"><div><p className="text-[#FFC52D] font-bold">São Mateus · Município de São Paulo · Brasil</p><h1 className="text-4xl font-black mt-4">Aluguel de caçamba em São Mateus</h1><p className="mt-5 text-slate-200 leading-relaxed">Vai reformar a casa, trocar pisos ou retirar entulho da obra em São Mateus? Consulte a caçamba adequada ao volume, ao prazo e ao espaço para entrega. O atendimento da Fortera é confirmado para o endereço, por meio da rede de parceiros e afiliados.</p><a className="inline-block mt-6 bg-[#25D366] font-bold p-4 rounded-xl" target="_blank" rel="noopener noreferrer" href={getWhatsAppLink('Olá! Quero orçamento de caçamba em São Mateus, município de São Paulo — SP. Meu bairro e prazo: ')}>Pedir orçamento para São Mateus</a></div><img src={SITE_IMAGES.hero.src} alt="Caçamba Fortera amarela para descarte de entulho de reformas" width={1536} height={1024} fetchPriority="high" className="w-full h-auto rounded-2xl"/></div></section>
    <section className="max-w-5xl mx-auto px-6 py-12"><h2 className="text-3xl font-black">Informe São Mateus e o ponto da sua obra</h2><p className="mt-4 leading-relaxed">São Mateus é um distrito do município de São Paulo, e não uma cidade separada no estado. No formulário, selecione SP, preencha a cidade como São Paulo e indique São Mateus no bairro. Se você procura o município de São Mateus no Espírito Santo, consulte <a className="underline font-bold" href="/aluguel-de-cacamba/es/sao-mateus/">a página de São Mateus — ES</a>.</p><div className="grid md:grid-cols-2 gap-6 mt-7"><article className="p-6 bg-slate-50 rounded-xl"><h3 className="text-xl font-bold">Entrega em imóvel ou condomínio</h3><p className="mt-3">Confirme a largura da entrada, o espaço de manobra e os horários com a portaria. Envie fotos do local pelo WhatsApp para avaliar fiação, portões e acesso do caminhão antes de agendar.</p></article><article className="p-6 bg-slate-50 rounded-xl"><h3 className="text-xl font-bold">Colocação na rua e retirada</h3><p className="mt-3">Informe o endereço e a vaga pretendida. A colocação em via pública precisa respeitar as regras da Prefeitura de São Paulo. Confirme com o atendimento as condições aplicáveis ao ponto de entrega e mantenha o entulho dentro da borda.</p></article></div></section>
    <LocalRentalDetails location="São Mateus, São Paulo"/>
    <section className="max-w-5xl mx-auto px-6 py-12"><h2 className="text-3xl font-black mb-5">Solicitar orçamento em São Mateus</h2><QuoteForm initialUf="SP" initialCity="São Paulo"/><p className="text-sm text-slate-600 mt-4">No campo bairro, informe São Mateus e a localização da sua obra. Disponibilidade e valor são confirmados no atendimento.</p></section>
  </div>;
}
